workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - build
  - test
  - analyze

variables:
  FLUTTER_VERSION: "3.27.4"
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache
    - build

# Code auschecken und Flutter installieren
default:
  image: cirrusci/flutter:${FLUTTER_VERSION}
  before_script:
    - flutter --version
    - flutter pub get

# Build Job
build:
  stage: build
  tags:
    - flutter
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week

# Test Job
test:
  stage: test
  tags:
    - flutter
  script:
    - flutter test

# Analyze Job
analyze:
  stage: analyze
  tags:
    - flutter
  script:
    - flutter analyze